services:
  billsender:
    image: lexabernal/bill_sender:arm64
    environment:
      - PORT=3000
      - HOST=microtech.icu
      - SMTP_SERVER=smtp.mailersend.net
      - SMTP_PORT=587
      - SMTP_LOGIN=MS_xJlnpH@microtech.icu
      - SMTP_PASSWORD=3DxIp0kA1aIaPuvu
      - DB_HOST=mariadb
      - DB_PORT=3307
      - DB_USER=root
      - DB_PASSWORD=my-password
      - DATABASE=MICROTECH
    ports:
      - "8888:3000"
