services:
  billsender:
    image: lexabernal/payment:arm64
    environment:
      - PORT=3000
      - HOST=microtech.icu
      - DB_HOST=mariadb
      - DB_PORT=3307
      - DB_USER=root
      - DB_PASSWORD=my-password
      - DATABASE=MICROTECH
    ports:
      - "8889:3000"
